from flask_sqlalchemy import SQLAlchemy
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime

# database object
db = SQLAlchemy()

class User(UserMixin, db.Model):
    """User model for storing user info"""
    __tablename__ = 'users'

    # primary key
    id = db.Column(db.Integer, primary_key=True)

    # username (unique and required)
    username = db.Column(db.String(80), unique=True, nullable=False, index=True)

    # password hash (encrypted, never plain text)
    password_hash = db.Column(db.String(200), nullable=False)

    # registration time
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

    # relationship: one user can upload many images
    images = db.relationship('Image', backref='uploader', lazy='dynamic')

    def set_password(self, password):
        """Hash and set password"""
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        """Verify password"""
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'


class Image(db.Model):
    """Image model for storing pet photos"""
    __tablename__ = 'images'

    # primary key
    id = db.Column(db.Integer, primary_key=True)

    # image caption/title
    caption = db.Column(db.String(200))

    # original image URL (full URL in Azure Blob Storage)
    original_url = db.Column(db.String(500), nullable=False)

    # thumbnail URL (generated by Azure Function)
    thumbnail_url = db.Column(db.String(500))

    # upload time
    upload_date = db.Column(db.DateTime, default=datetime.utcnow, index=True)

    # foreign key to users table
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    def __repr__(self):
        return f'<Image {self.id}: {self.caption}>'

